version: '3'

services:

  nginx:
    image: "user3437721/nginx-lua"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    build:
      context: "."
      dockerfile: Dockerfile_nginx
    ports:
      - "80:80"
    volumes:
      - ./app/nginx:/etc/nginx/conf.d
    depends_on:
      - go-api

#  nginx:
#    image: nginx:latest
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf

  go-api:
    build:
      context: .
    image: go-app:latest
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: always
    ports:
      - "8080:8080"
#    depends_on:
#      - redis
    env_file:
      .env


#  redis:
#    image: redis
#    container_name: backoffice-redis
#    restart: always
#    ports:
#      - "6379:6379"
