FROM openresty/openresty:latest

COPY nginx/app.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY nginx/cache_script.lua /usr/share/nginx/html/cache_script.lua
COPY nginx/cache_script.lua /usr/share/nginx/html/md_5.lua
COPY nginx/invalidator.lua /usr/share/nginx/html/invalidator.lua

EXPOSE 80

CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]

