FROM openresty/openresty:latest

COPY nginx/app.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY nginx/cache_redis.lua /usr/share/nginx/html/cache_redis.lua

EXPOSE 80

CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]

